---
kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker
    when:
      event: [push]
      branch:
        - master
    settings:
      registry: https://registry.webkom.dev
      repo: registry.webkom.dev/webkom/abakus-fwd
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
        - version-${DRONE_COMMIT_SHA:0:7}

---
kind: signature
hmac: de38fa1906d12a8a30fc01b1461e2bb552b538670633e2baf91c1ed6db180d8d
